# Generated by Django 4.1.7 on 2023-02-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_language_alter_doctordetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetail',
            name='languages',
        ),
        migrations.AddField(
            model_name='doctordetail',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.language'),
        ),
    ]
